a=input("Enter The First No:")
a=int(a)
b=input("Enter The Second No:")
b=int(b)
print("Addition of two No.",a+b)
print("Substraction of two No.",a-b)
print("Multiplication of two No.",a*b)
print("Division of two No.",a/b)
print("Average two no:",(a+b)/2)
print("Squre of no.a",a*a)
print("Squre of no.b",b*b)
print("Cube of no.a",a*a*a)
print("Cube of no.b",b*b*b)
